version: "3.9"
services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchainkey.pem:/etc/ssl/cert.pem
      - ./primarykey.pem:/etc/ssl/key.pem
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
    env_file: common.env
    environment:
      FLASK_ENV: development
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    command: npm start
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80
volumes:
  db_data:
