version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
    env_file: common.env
    environment:
      FLASK_ENV: development
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    command: npm start
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80
volumes:
  dbdata: