# syntax=docker/dockerfile:1
# FROM jjanzic/docker-python3-opencv
FROM borda/docker_python-opencv-ffmpeg
WORKDIR /code
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
COPY . .
CMD ["flask", "run"]